import type { Metadata } from "next";
import "./globals.css";
import ReactQuery from "@/components/reactQuery";
import Navbar from "@/components/navbar";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/components/nextauth";
import { ReactNode } from "react";
import { Session } from "next-auth";
import socket from "@/utils/socket.utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en" data-theme="bumblebee">
      <body>
        <NextAuthProvider session={session}>
          <ReactQuery>{children}</ReactQuery>
        </NextAuthProvider>
        <Toaster
          position="top-center"
          // toastOptions={{
          //   className: 'top-10',
          //   style: {
          //     top: '100px'
          //   }
          // }}
          toastOptions={{
            duration: 1500,
          }}
          containerStyle={{
            top: 80,
            zIndex: 999999999,
          }}
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
